# example for Crud plugin
# assumes plugin is in path/to/app/Plugin/Crud
cd path/to/app

# Clone the repo down
git clone git@github.com:FriendsOfCake/travis.git vendor/travis

# Export some environment variables for running the setup script
export COPYRIGHT_YEAR=2014
export GITHUB_USERNAME="stefanneculai"
export PLUGIN_PATH="Plugin/Froala"
export PLUGIN_NAME="Froala"
export REPO_NAME="wysiwyg-cake"
export YOUR_NAME="Stefan Neculai"

# Run the setup
./vendor/travis/setup.sh

# Remove this repository when you are done
rm -rf vendor/travis